# params.yaml
# only_sklearn_pipeline
index_col: 'customer_id'
target_col: 'target'
one_hot_drop: 'if_binary'
handle_unknown: 'ignore'
strategy_num: 'mean'
strategy: 'most_frequent'
C: 1.0
penalty: 'l2'
class_weight: 'balanced'
max_iter: 100
n_splits: 5
metrics: ['f1', 'roc_auc']
n_jobs: -1